version: '3.8'
services:

  cat1:
    build: .
    container_name: cat1
    environment:
      - IMAGE_PATH=../images/cat1.png
    ports:
      - "8081:80"
    restart: unless-stopped

  cat2:
    build: .
    container_name: cat2
    environment:
      - IMAGE_PATH=../images/cat2.png
    ports:
      - "8082:80"
    restart: unless-stopped

  cat3:
    build: .
    container_name: cat3
    environment:
      - IMAGE_PATH=../images/cat3.png
    ports:
      - "8083:80"
    restart: unless-stopped

  cat_cached:
    build: .
    container_name: cat_cached
    environment:
      - IMAGE_PATH=../images/cat_cached.png
    ports:
      - "8084:80"
    restart: unless-stopped

  balancer:
    image: nginx:alpine
    container_name: balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cat1
      - cat2
      - cat3
      - cat_cached
    restart: unless-stopped

networks:
  default:
    driver: bridge
